routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('user', 'UserController')->middleware(['auth','can:access,App\User']);
Route::resource('listing', 'ListingController')->middleware(['auth','can:access,App\User']);

app/Listing.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Listing extends Model
{

 
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Laravel\Passport\HasApiTokens;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable,HasApiTokens;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password','type',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
   
}

app/Http/Controllers/AuthController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Listing;
use Illuminate\Support\Facades\Auth;


class AuthController extends Controller
{
    public function login(){ 
        if(Auth::attempt(['email' => request('email'), 'password' => request('password')])){ 
           $user = Auth::user(); 
           $token['token'] =  $user->createToken('PartB')-> accessToken; 
            return response()->json(['user_id'=>$user->id,'token'=>$token['token'] ,'status'=>['code'=> 200 ,'message'=>'Access Granted']]); 
          } else{ 
           return response()->json(['error'=>'Unauthorised'], 401); 
           } 
        }

   
  
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/ListingController.php
<?php

namespace App\Http\Controllers;

use App\Listing;
use Auth;
use Illuminate\Http\Request;

class ListingController extends Controller
{
  
    public function index()
    {
        $list=Listing::all();
        $data=compact('list');
        return view('listing.manage-listing',$data);
    }

 
    public function create()
    {
        return view('listing.add-listing');
    }

    
    public function store(Request $request)
    {
        $list=new Listing;
        $list->list_name=$request->name;
        $list->address=$request->address;
        $list->latitude=$request->latitude;
        $list->longitude=$request->longitude;
        $list->submitter_id=Auth::user()->id;
        $list->save();
        return redirect()->route('listing.index');
    }

    public function show(Listing $listing)
    {
        //
    }

  
    public function edit(Listing $listing)
    {
        $data=compact('listing');
        return view('listing.edit-listing',$data);
    }

    public function update(Request $request, Listing $listing)
    {

        $listing->list_name=$request->name;
        $listing->address=$request->address;
        $listing->latitude=$request->latitude;
        $listing->longitude=$request->longitude;
        $listing->submitter_id=Auth::user()->id;
        $listing->save();
        return redirect()->route('listing.index');
    }

  
    public function destroy(Listing $listing)
    {
        $listing->delete();
        return redirect()->route('listing.index');
    }
    public function apilisting(Request $request){
        $listing =Listing::where('submitter_id',$request->user_id)->get();
      foreach($listing as $list) {
        $list->distance = number_format($this->distance($request->latitude,$request->longitude,$list->latitude,$list->longitude),3);
      }
      return response()->json(['listing'=>$listing,'status'=>['code'=>200,'message'=>'Listing successfully retrieved']]);
    }
    
    function distance($lat1, $lon1, $lat2, $lon2) {
        if (($lat1 == $lat2) && ($lon1 == $lon2)) {
          return 0;
        }
        else {
          $theta = $lon1 - $lon2;
          $dist = sin(deg2rad($lat1)) * sin(deg2rad($lat2)) +  cos(deg2rad($lat1)) * cos(deg2rad($lat2)) * cos(deg2rad($theta));
          $dist = acos($dist);
          $dist = rad2deg($dist);
          $miles = $dist * 60 * 1.1515;
            return ($miles * 1.609344);
        
        }
      }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $user =User::all();
        $data=compact('user');
        return view('admindashboard.manage-user',$data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admindashboard.add-user');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $user =new User;
        $user->name = $request->name;
        $user->email = $request->email;
        $user->password = Hash::make($request->password);
        $user->type = $request->type;
        $user->save();
      return redirect()->route('user.index');
    }

    
    public function show(User $user)
    {
        //
    }

   
    public function edit(User $user)
    {
        $data=compact('user');
        return view('admindashboard.edit-user',$data);
    }

    
    public function update(Request $request, User $user)
    {
        $user->name=$request->name;
        $user->email=$request->email;
        $user->type=$request->type;
        $user->save();
        return redirect()->route('user.index');
    }

   
    public function destroy(User $user)
    {
       $user->delete();
       return redirect()->route('user.index');

     
    }
}

resources/views/admindashboard/add-user.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-10">
            <div class="card">
                <div class="card-header"> Admin Dashboard -> Create User</div>

                <div class="card-body ">
                <form  method="POST"  action="{{route('user.store')}}"> 
                    {{ csrf_field() }}
                    <div class="row">
                        <div class="col-md-10 ">
                            <label>Name</label>
                            <input type="text" name="name" class="form-control" required>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-10">
                            <label>Email</label>
                            <input type="email" name="email" class="form-control" required>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-10">
                            <label>Password</label>
                            <input type="password" name="password" class="form-control" required>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-10">
                            <label>Select User Type</label>
                            <select  name="type" class="form-control" required>
                                <option value="u">user </option>
                                <option value="a">admin </option>
                            </select>
                             
                        </div>
                    </div>
                    <button class="btn btn-primary mt-2 float-right" type="submit">Create User</button>
                    </form>

                   
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admindashboard/edit-user.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-10">
            <div class="card">
                <div class="card-header"> Admin Dashboard -> Edit User</div>

                <div class="card-body ">
                <form  method="POST"  action="{{route('user.update',$user->id)}}"> 
                        @method('PATCH')
                    {{ csrf_field() }}
                    <div class="row">
                        <div class="col-md-10 ">
                            <label>Name</label>
                        <input type="text" name="name" class="form-control" value="{{$user->name}}" required>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-10">
                            <label>Email</label>
                            <input type="email" name="email" class="form-control" value="{{$user->email}}" required>
                        </div>
                    </div>
                
                    <div class="row">
                        <div class="col-md-10">
                            <label>Select User Type</label>
                            <select  name="type" class="form-control" required>
                                
                                <option value="u" @if ($user->type == 'u' ) 
                                    {{'selected'}}
                                @endif>user </option>
                                <option value="a" @if ($user->type == 'a') 
                                        {{'selected'}}
                                    @endif>admin </option>
                                
                            </select>
                             
                        </div>
                    </div>
                    <button class="btn btn-primary mt-2 float-right" type="submit">Edit User</button>
                    </form>

                   
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admindashboard/manage-user.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
            <div class="card-header"> Admin Dashboard -> Manage User  <a class="btn btn-primary float-right" href="{{route('user.create')}}">Add User</a></div>

                <div class="card-body ">
                <table class="table">
                    <thead>
                        <th>User Id</th>
                        <th>User Name</th>
                        <th>User Email</th>
                        <th>User Type </th>
                        <th >Action</th>
                    </thead>
                    @forelse ($user as $item)
                    <tbody>   
                    <td>{{$item->id}}</td>
                    <td>{{$item->name}}</td>
                    <td>{{$item->email}}</td>
                            <td>@if ($item->type == 'u')
                                {{'user'}}
                            @else
                                {{'admin'}}
                            @endif </td>
                            <td >
                                <div class="row"><a href="{{route('user.edit',$item->id)}}" class="btn btn-warning">Edit</a>&nbsp;
                                <form action="{{route('user.destroy',$item->id)}}" method="POST">
                                        @method('DELETE')
                                        @csrf
                                        <button class="btn btn-danger">Delete</button>
                                    </form></div>
                               </td>                
                  </tbody>
                            @empty
                            <td colspan="8"> No data</td>
                            @endforelse

                </table>
                   
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Part B') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">
                        @auth
                            @if(Auth::user()->type =='a')
                             <li class="nav-item">
                            <a class="nav-link" href="{{route('user.index')}}">Admin Dashboard</a>
                                </li>
                                <li class="nav-item">
                                        <a class="nav-link" href="{{route('listing.index')}}">Listing Dashboard</a>
                                            </li>
                            @endif
                        @endauth
                           
                            </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/listing/add-listing.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-10">
            <div class="card">
                <div class="card-header"> List Dashboard -> Create List</div>
             
                <div class="card-body ">
                <form  method="POST"  action="{{route('listing.store')}}"> 
                    {{ csrf_field() }}
                    <div class="row">
                        <div class="col-md-10 ">
                            <label> List Name</label>
                            <input type="text" name="name" class="form-control" required>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-10">
                            <label>List Address</label>
                            <input type="text" name="address" class="form-control" required>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-10">
                            <label>Latitude</label>
                            <input type="text" name="latitude" class="form-control" required>
                        </div>
                    </div>
                    <div class="row">
                            <div class="col-md-10">
                                <label>Longitude</label>
                                <input type="text" name="longitude" class="form-control" required>
                            </div>
                        </div>
                    <button class="btn btn-primary mt-2 float-right" type="submit">Create List</button>
                    </form>

                   
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/listing/edit-listing.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-10">
            <div class="card">
                <div class="card-header"> List Dashboard -> Edit List</div>

                <div class="card-body ">
                <form  method="POST"  action="{{route('listing.update',$listing->id)}}"> 
                        @method('PATCH')
                    {{ csrf_field() }}
                    <div class="row">
                            <div class="col-md-10 ">
                                <label> List Name</label>
                            <input type="text" name="name" value="{{$listing->list_name}}" class="form-control" required>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-10">
                                <label>List Address</label>
                            <input type="text" name="address" value="{{$listing->address}}" class="form-control" required>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-10">
                                <label>Latitude</label>
                            <input type="text" name="latitude"  value="{{$listing->latitude}}" class="form-control" required>
                            </div>
                        </div>
                        <div class="row">
                                <div class="col-md-10">
                                    <label>Longitude</label>
                                    <input type="text" name="longitude" value="{{$listing->longitude}}" class="form-control" required>
                                </div>
                            </div>
                        <button class="btn btn-primary mt-2 float-right" type="submit">Update List</button>
                        </form>
    

                   
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/listing/manage-listing.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
            <div class="card-header"> List Dashboard -> Manage List  <a class="btn btn-primary float-right" href="{{route('listing.create')}}">Add List</a></div>

                <div class="card-body ">
                <table class="table">
                    <thead>
                        <th>List Id</th>
                        <th>List Name</th>
                        <th>List Address</th>
                        <th>Latitude </th>
                        <th >Longititude</th>
                        <th >Submitter_id</th>
                        <th>Action</th>
                    </thead>
                    @forelse ($list as $item)
                    <tbody>   
                    <td>{{$item->id}}</td>
                    <td>{{$item->list_name}}</td>
                    <td>{{$item->address}}</td>
                    <td>{{$item->latitude }}</td>
                    <td>{{$item->longitude}}</td>
                    <td>{{$item->submitter_id}}</td>        
                    <td >
                                <div class="row"><a href="{{route('listing.edit',$item->id)}}" class="btn btn-warning">Edit</a>&nbsp;
                                <form action="{{route('listing.destroy',$item->id)}}" method="POST">
                                        @method('DELETE')
                                        @csrf
                                        <button class="btn btn-danger">Delete</button>
                                    </form></div>
                               </td>                
                  </tbody>
                            @empty
                            <td colspan="8"> No data</td>
                            @endforelse

                </table>
                   
                </div>
            </div>
        </div>
    </div>
</div>
@endsection